[workspace]
resolver = "2"
members = [
    "wasm-core",
    "crates/*",
    "crates/polymarket-oracle",
    "crates/memory-node"
]

[workspace.dependencies]
tokio = { version = "1.37.0", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
extism = "1.2"
axum = "0.7"
alloy = { version = "0.1", features = ["full"] }
